### ISSUE TITLE
Unmatched slashes cause infinite loop.

### ISSUE THREAD

**Issue by doowb** [jonschlinkert/expand-object#2]
I was trying this out with a value like a filepath: `src:**/*.js` and I get an `RangeError: Invalid string length`.

This is happening here: https://github.com/jonschlinkert/expand-object/blob/master/index.js#L208-L213

I think that if statement is to handle not splitting when a regex is in the value. I was able to make a change so it'll work if that's the only slash and is in the last value, but I wasn't able to get it work for other cases:  `src:**/*.js|dest:_gh_pages/assets` for instance.

Maybe you have an idea on how this can be escaped or handled. I'm not quite sure.

**Comment by jonschlinkert** [comment]
thanks I'll take a look at it
